spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/cartao
    username: cartao
    password: cartao
    continue-on-error: true
  jpa:
    open-in-view: false
    show-sql: true
    format-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          batch_size: 50
    defer-datasource-initialization: true
  sql:
    init:
      data-locations: classpath:data-postgres.sql
      mode: always
  liquibase:
    enabled: false
    change-log: classpath:db/changelog/changelog-local.xml
